### ISSUE TITLE
No module named 'extern.ldm_zero123'

### ISSUE THREAD

**Issue by Asianfleet** [chinhsuanwu/ifusion#2]
The command I ran:

python main.py data.image_dir=asset/sorter

The output:

[INFO] Loading Zero123...
[INFO] Loading model from ldm/ckpt/zero123-xl.ckpt
Traceback (most recent call last):
  File "/data/AIMH/pkgs/3D/Gen/ifusion/main.py", line 28, in <module>
    main(config)
  File "/data/AIMH/pkgs/3D/Gen/ifusion/main.py", line 9, in main
    model = parse_model(config.model)
  File "/data/AIMH/pkgs/3D/Gen/ifusion/util/util.py", line 32, in parse_model
    model = getattr(models, config.name[0].upper() + config.name[1:])(**config.args)
  File "/data/AIMH/pkgs/3D/Gen/ifusion/model/zero123.py", line 39, in __init__
    self.configure()
  File "/data/AIMH/pkgs/3D/Gen/ifusion/model/zero123.py", line 46, in configure
    self.model: LatentDiffusion = load_model_from_config(
  File "/data/AIMH/pkgs/3D/Gen/ifusion/ldm/util.py", line 39, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/data/AIMH/pkgs/3D/Gen/ifusion/ldm/util.py", line 27, in instantiate_from_config
    return get_obj_from_str(config["target"])(**kwargs, **config.get("params", dict()))
  File "/data/AIMH/pkgs/3D/Gen/ifusion/ldm/util.py", line 17, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/data/AIMH/envs/IFU/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'extern.ldm_zero123'

**Comment by chinhsuanwu** [comment]
Can you show me your config file? Note that our implementation of Zero123 is different from [threestudio](https://github.com/threestudio-project/threestudio).
