### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './ifusion/ldm/ckpt/sd-objaverse-finetune-c_concat-256.yaml'

### ISSUE THREAD

**Issue by mohit-choithwani** [chinhsuanwu/ifusion#3]
Hi, Thank you for publishing this great work. While executing this command `'python main.py data.image_dir=asset/sorter'` I got the following error. Could you please help me with this?
```
(ifusion) root@blues:~/root/models/ifusion$ python3 main.py data.image_dir=asset/sorter/
2024-01-22 21:53:46.675346: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-22 21:53:46.675378: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-22 21:53:46.676629: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-22 21:53:46.682665: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-22 21:53:47.403899: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.12.1-git20200711.33e2d80-dfsg1-0.6 is an invalid version and will not be supported in a future release
  warnings.warn(
[INFO] Loading Zero123...
Traceback (most recent call last):
  File "/home/root/models/ifusion/main.py", line 28, in <module>
    main(config)
  File "/home/root/models/ifusion/main.py", line 9, in main
    model = parse_model(config.model)
  File "/home/root/models/ifusion/util/util.py", line 32, in parse_model
    model = getattr(models, config.name[0].upper() + config.name[1:])(**config.args)
  File "/home/root/models/ifusion/model/zero123.py", line 39, in __init__
    self.configure()
  File "/home/root/models/ifusion/model/zero123.py", line 44, in configure
    self.pretrained_config = OmegaConf.load(self.config.pretrained_config)
  File "/home/root/.local/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/root/models/ifusion/ldm/ckpt/sd-objaverse-finetune-c_concat-256.yaml'

```

**Comment by chinhsuanwu** [comment]
Thanks for pointing out. We just added.
